### ISSUE TITLE
How to get barcode Component ?

### ISSUE THREAD

**Issue by M0nsieurT** [sx2008/FBarcode#1]
Hi, 

I'm trying to compile a project with your sources, unfortunately the website you mention does not exist anymore.

How to get barcode Component ?

**Comment by sx2008** [comment]
Just download the source code from GitHub:
https://github.com/sx2008/FBarcode/archive/master.zip
How to install a Delphi component depends on your Delphi Version.
If your aren't familiar with this task search for instructions on Google or your prefered search engine:
https://www.google.de/#q=how%20to%20install%20delphi%207%20component
